global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'laravel_app'
    metrics_path: /metrics
    static_configs:
      - targets: ['webserver:80']  
